name: ai_review.yml
on:
  pull_request:
    types: [opened, synchronize]  # PR이 열리거나 코드가 업데이트 될 때

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # 전체 이력을 가져와 Diff 분석을 원활하게 함

      - name: AI Code Review
        uses: sshnaidm/gemini-code-review-action@v2
        with:
          gemini-key: ${{secrets.GEMINI_API_KEY}}
          model: "gemini-1.5-flash"